## @param nameOverride String to partially override common.names.fullname template (will maintain the release name)
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname template
fullnameOverride: ""
## @param commonLabels Add labels to all the deployed resources
commonLabels: {}
## @param commonAnnotations Add annotations to all the deployed resources
commonAnnotations: {}

services:
  main:
    type: ClusterIP
    ports:
      rest: 808
      sql: 20800
      thin: 40900
      memcached: 1123
    sessionAffinity: None
  headless:
    type: ClusterIP
    clusterIP: None
    ports:
      rest: 8080
      sql: 10800
      thin: 10900
      memcached: 11211
    sessionAffinity: None
  memcached:
    type: ClusterIP
    clusterIP: None
    ports:
      memcached: 11211
    sessionAffinity: None
